SENDING_KEYS = [
    "sn",
    "safetyType",
    "battMode",
    "solarSell",
    "pvMaxLimit",
    "energyMode",
    "peakAndVallery",
    "sysWorkMode",
    "sellTime1",
    "sellTime2",
    "sellTime3",
    "sellTime4",
    "sellTime5",
    "sellTime6",
    "sellTime1Pac",
    "sellTime2Pac",
    "sellTime3Pac",
    "sellTime4Pac",
    "sellTime5Pac",
    "sellTime6Pac",
    "cap1",
    "cap2",
    "cap3",
    "cap4",
    "cap5",
    "cap6",
    "sellTime1Volt",
    "sellTime2Volt",
    "sellTime3Volt",
    "sellTime4Volt",
    "sellTime5Volt",
    "sellTime6Volt",
    "sellTime1En",
    "sellTime2En",
    "sellTime3En",
    "sellTime4En",
    "sellTime5En",
    "sellTime6En",
    "zeroExportPower",
    "solarMaxSellPower",
    "gridPeakShaving",
    "generatorStartCap",
    "time1on",
    "time2on",
    "time3on",
    "time4on",
    "time5on",
    "genTime1on",
    "genTime2on",
    "genTime3on",
    "genTime4on",
    "genTime5on",
    "batteryLowCap",
    "mondayOn",
    "tuesdayOn",
    "wednesdayOn",
    "thursdayOn",
    "fridayOn",
    "saturdayOn",
    "sundayOn",
    "time6on",
    "genTime6on",
]

BATTERY_SEND = list({
    "sn": "2211166856",
    "safetyType": "0",
    "battMode": "-1",
    "batteryCap": "500",
    "batteryMaxCurrentCharge": "1",
    "batteryMaxCurrentDischarge": "1",
    "batteryEmptyV": "45",
    "batteryImpedance": "8",
    "batteryEfficiency": "99",
    "batteryShutdownCap": "15",
    "batteryLowCap": "18",
    "batteryRestartCap": "50",
    "batteryShutdownVolt": "46",
    "batteryLowVolt": "47.5",
    "batteryRestartVolt": "52",
    "batteryOn": "1",
    "floatVolt": "55.2",
    "lithiumMode": "0",
    "sdChargeOn": "1",
    "sdStartCap": "15",
    "sdBatteryCurrent": "40",
    "genChargeOn": "0",
    "sdStartVol": "undefined",
    "gridSignal": "1",
    "generatorStartVolt": "0",
    "generatorStartCap": "10",
    "generatorBatteryCurrent": "40",
    "equChargeCycle": "90",
    "equChargeTime": "0",
    "absorptionVolt": "57.6",
    "equVoltCharge": "57.6",
    "tempco": "0",
    "genSignal": "0",
    "sdStartVolt": "49",
    "generatorForcedStart": "0",
    "bmsErrStop": "0",
    "signalIslandModeEnable": "0",
    "lowPowerMode": "0",
    "disableFloatCharge": "1",
    "lowNoiseMode": "8000",
    "flag2": "0",
}.keys())
